// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * AdminListResponse
 */
export type AdminListResponse = {
    /**
     * Admins
     */
    admins: Array<AdminProfileResponse>;
    /**
     * Total
     */
    total: number;
};

/**
 * AdminProfileResponse
 */
export type AdminProfileResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Verified
     */
    is_verified: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AdminRegisterRequest
 */
export type AdminRegisterRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ApproveAdminResponse
 */
export type ApproveAdminResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * ChatMessage
 */
export type ChatMessage = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
    /**
     * Query
     */
    query: string;
};

/**
 * ChatResponse
 */
export type ChatResponse = {
    /**
     * Reply
     */
    reply: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * ContinueChatRequest
 *
 * Resume an existing conversation by its ID.
 */
export type ContinueChatRequest = {
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Query
     */
    query: string;
};

/**
 * ContinueChatResponse
 *
 * Returned by the continue-chat endpoint.
 */
export type ContinueChatResponse = {
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Reply
     */
    reply: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * ConversationHistoryResponse
 */
export type ConversationHistoryResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Conversation History
     */
    conversation_history: Array<ChatMessage>;
    /**
     * Total Messages
     */
    total_messages: number;
};

/**
 * ConversationSummary
 *
 * One conversation belonging to a user — used in list views.
 */
export type ConversationSummary = {
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Title
     */
    title: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Message Count
     */
    message_count: number;
};

/**
 * CreateUserRequest
 *
 * Admin creates a user and sets an initial password.
 */
export type CreateUserRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LogoutRequest
 */
export type LogoutRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * MessageResponse
 *
 * Generic envelope returned by every endpoint.
 */
export type MessageResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: unknown | null;
};

/**
 * NewChatRequest
 *
 * Start a brand-new conversation.
 * An optional title can be supplied upfront; if omitted the conversation
 * will have no title until the caller renames it later.
 */
export type NewChatRequest = {
    /**
     * Query
     */
    query: string;
    /**
     * Title
     *
     * Optional human-readable title for the new conversation.
     */
    title?: string | null;
};

/**
 * NewChatResponse
 *
 * Returned by the new-chat endpoint — includes the conversation_id so the
 * caller can reference the conversation in subsequent continue-chat calls.
 */
export type NewChatResponse = {
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Reply
     */
    reply: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * PendingAdminResponse
 */
export type PendingAdminResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * RefreshTokenRequest
 */
export type RefreshTokenRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * RenameConversationRequest
 */
export type RenameConversationRequest = {
    /**
     * Title
     */
    title: string;
};

/**
 * RenameConversationResponse
 */
export type RenameConversationResponse = {
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Message
     */
    message: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserConversationsResponse
 */
export type UserConversationsResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Conversations
     */
    conversations: Array<ConversationSummary>;
};

/**
 * UserListResponse
 */
export type UserListResponse = {
    /**
     * Users
     */
    users: Array<UserProfileResponse>;
    /**
     * Total
     */
    total: number;
};

/**
 * UserProfileResponse
 */
export type UserProfileResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Role
     */
    role: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Verified
     */
    is_verified: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Last Login At
     */
    last_login_at?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RegisterAdminAuthRegisterAdminPostData = {
    body: AdminRegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register/admin';
};

export type RegisterAdminAuthRegisterAdminPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterAdminAuthRegisterAdminPostError = RegisterAdminAuthRegisterAdminPostErrors[keyof RegisterAdminAuthRegisterAdminPostErrors];

export type RegisterAdminAuthRegisterAdminPostResponses = {
    /**
     * Successful Response
     */
    201: MessageResponse;
};

export type RegisterAdminAuthRegisterAdminPostResponse = RegisterAdminAuthRegisterAdminPostResponses[keyof RegisterAdminAuthRegisterAdminPostResponses];

export type LoginAuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type RefreshTokensAuthRefreshPostData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshTokensAuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshTokensAuthRefreshPostError = RefreshTokensAuthRefreshPostErrors[keyof RefreshTokensAuthRefreshPostErrors];

export type RefreshTokensAuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type RefreshTokensAuthRefreshPostResponse = RefreshTokensAuthRefreshPostResponses[keyof RefreshTokensAuthRefreshPostResponses];

export type LogoutAuthLogoutPostData = {
    body: LogoutRequest;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutAuthLogoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutAuthLogoutPostError = LogoutAuthLogoutPostErrors[keyof LogoutAuthLogoutPostErrors];

export type LogoutAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type LogoutAuthLogoutPostResponse = LogoutAuthLogoutPostResponses[keyof LogoutAuthLogoutPostResponses];

export type GetMeAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetMeAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserProfileResponse;
};

export type GetMeAuthMeGetResponse = GetMeAuthMeGetResponses[keyof GetMeAuthMeGetResponses];

export type IngestDataApiV1SuperadminIngestPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/superadmin/ingest';
};

export type IngestDataApiV1SuperadminIngestPostResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type IngestDataApiV1SuperadminIngestPostResponse = IngestDataApiV1SuperadminIngestPostResponses[keyof IngestDataApiV1SuperadminIngestPostResponses];

export type ListAdminsApiV1SuperadminAdminsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/superadmin/admins';
};

export type ListAdminsApiV1SuperadminAdminsGetResponses = {
    /**
     * Successful Response
     */
    200: AdminListResponse;
};

export type ListAdminsApiV1SuperadminAdminsGetResponse = ListAdminsApiV1SuperadminAdminsGetResponses[keyof ListAdminsApiV1SuperadminAdminsGetResponses];

export type ListPendingAdminsApiV1SuperadminAdminsPendingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/superadmin/admins/pending';
};

export type ListPendingAdminsApiV1SuperadminAdminsPendingGetResponses = {
    /**
     * Response List Pending Admins Api V1 Superadmin Admins Pending Get
     *
     * Successful Response
     */
    200: Array<PendingAdminResponse>;
};

export type ListPendingAdminsApiV1SuperadminAdminsPendingGetResponse = ListPendingAdminsApiV1SuperadminAdminsPendingGetResponses[keyof ListPendingAdminsApiV1SuperadminAdminsPendingGetResponses];

export type ApproveAdminApiV1SuperadminAdminsAdminIdApprovePatchData = {
    body?: never;
    path: {
        /**
         * Admin Id
         */
        admin_id: string;
    };
    query?: never;
    url: '/api/v1/superadmin/admins/{admin_id}/approve';
};

export type ApproveAdminApiV1SuperadminAdminsAdminIdApprovePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveAdminApiV1SuperadminAdminsAdminIdApprovePatchError = ApproveAdminApiV1SuperadminAdminsAdminIdApprovePatchErrors[keyof ApproveAdminApiV1SuperadminAdminsAdminIdApprovePatchErrors];

export type ApproveAdminApiV1SuperadminAdminsAdminIdApprovePatchResponses = {
    /**
     * Successful Response
     */
    200: ApproveAdminResponse;
};

export type ApproveAdminApiV1SuperadminAdminsAdminIdApprovePatchResponse = ApproveAdminApiV1SuperadminAdminsAdminIdApprovePatchResponses[keyof ApproveAdminApiV1SuperadminAdminsAdminIdApprovePatchResponses];

export type DeactivateAdminApiV1SuperadminAdminsAdminIdDeactivatePatchData = {
    body?: never;
    path: {
        /**
         * Admin Id
         */
        admin_id: string;
    };
    query?: never;
    url: '/api/v1/superadmin/admins/{admin_id}/deactivate';
};

export type DeactivateAdminApiV1SuperadminAdminsAdminIdDeactivatePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeactivateAdminApiV1SuperadminAdminsAdminIdDeactivatePatchError = DeactivateAdminApiV1SuperadminAdminsAdminIdDeactivatePatchErrors[keyof DeactivateAdminApiV1SuperadminAdminsAdminIdDeactivatePatchErrors];

export type DeactivateAdminApiV1SuperadminAdminsAdminIdDeactivatePatchResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeactivateAdminApiV1SuperadminAdminsAdminIdDeactivatePatchResponse = DeactivateAdminApiV1SuperadminAdminsAdminIdDeactivatePatchResponses[keyof DeactivateAdminApiV1SuperadminAdminsAdminIdDeactivatePatchResponses];

export type DeleteAdminApiV1SuperadminAdminsAdminIdDeleteData = {
    body?: never;
    path: {
        /**
         * Admin Id
         */
        admin_id: string;
    };
    query?: never;
    url: '/api/v1/superadmin/admins/{admin_id}';
};

export type DeleteAdminApiV1SuperadminAdminsAdminIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAdminApiV1SuperadminAdminsAdminIdDeleteError = DeleteAdminApiV1SuperadminAdminsAdminIdDeleteErrors[keyof DeleteAdminApiV1SuperadminAdminsAdminIdDeleteErrors];

export type DeleteAdminApiV1SuperadminAdminsAdminIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteAdminApiV1SuperadminAdminsAdminIdDeleteResponse = DeleteAdminApiV1SuperadminAdminsAdminIdDeleteResponses[keyof DeleteAdminApiV1SuperadminAdminsAdminIdDeleteResponses];

export type ListAllUsersApiV1SuperadminUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/superadmin/users';
};

export type ListAllUsersApiV1SuperadminUsersGetResponses = {
    /**
     * Successful Response
     */
    200: UserListResponse;
};

export type ListAllUsersApiV1SuperadminUsersGetResponse = ListAllUsersApiV1SuperadminUsersGetResponses[keyof ListAllUsersApiV1SuperadminUsersGetResponses];

export type GetUserApiV1SuperadminUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/superadmin/users/{user_id}';
};

export type GetUserApiV1SuperadminUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserApiV1SuperadminUsersUserIdGetError = GetUserApiV1SuperadminUsersUserIdGetErrors[keyof GetUserApiV1SuperadminUsersUserIdGetErrors];

export type GetUserApiV1SuperadminUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserProfileResponse;
};

export type GetUserApiV1SuperadminUsersUserIdGetResponse = GetUserApiV1SuperadminUsersUserIdGetResponses[keyof GetUserApiV1SuperadminUsersUserIdGetResponses];

export type ListMyUsersApiV1AdminUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/users';
};

export type ListMyUsersApiV1AdminUsersGetResponses = {
    /**
     * Successful Response
     */
    200: UserListResponse;
};

export type ListMyUsersApiV1AdminUsersGetResponse = ListMyUsersApiV1AdminUsersGetResponses[keyof ListMyUsersApiV1AdminUsersGetResponses];

export type CreateUserApiV1AdminUsersPostData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/users';
};

export type CreateUserApiV1AdminUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiV1AdminUsersPostError = CreateUserApiV1AdminUsersPostErrors[keyof CreateUserApiV1AdminUsersPostErrors];

export type CreateUserApiV1AdminUsersPostResponses = {
    /**
     * Successful Response
     */
    201: UserProfileResponse;
};

export type CreateUserApiV1AdminUsersPostResponse = CreateUserApiV1AdminUsersPostResponses[keyof CreateUserApiV1AdminUsersPostResponses];

export type DeleteUserApiV1AdminUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}';
};

export type DeleteUserApiV1AdminUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiV1AdminUsersUserIdDeleteError = DeleteUserApiV1AdminUsersUserIdDeleteErrors[keyof DeleteUserApiV1AdminUsersUserIdDeleteErrors];

export type DeleteUserApiV1AdminUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteUserApiV1AdminUsersUserIdDeleteResponse = DeleteUserApiV1AdminUsersUserIdDeleteResponses[keyof DeleteUserApiV1AdminUsersUserIdDeleteResponses];

export type GetMyUserApiV1AdminUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}';
};

export type GetMyUserApiV1AdminUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMyUserApiV1AdminUsersUserIdGetError = GetMyUserApiV1AdminUsersUserIdGetErrors[keyof GetMyUserApiV1AdminUsersUserIdGetErrors];

export type GetMyUserApiV1AdminUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserProfileResponse;
};

export type GetMyUserApiV1AdminUsersUserIdGetResponse = GetMyUserApiV1AdminUsersUserIdGetResponses[keyof GetMyUserApiV1AdminUsersUserIdGetResponses];

export type DeactivateUserApiV1AdminUsersUserIdDeactivatePatchData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/deactivate';
};

export type DeactivateUserApiV1AdminUsersUserIdDeactivatePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeactivateUserApiV1AdminUsersUserIdDeactivatePatchError = DeactivateUserApiV1AdminUsersUserIdDeactivatePatchErrors[keyof DeactivateUserApiV1AdminUsersUserIdDeactivatePatchErrors];

export type DeactivateUserApiV1AdminUsersUserIdDeactivatePatchResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeactivateUserApiV1AdminUsersUserIdDeactivatePatchResponse = DeactivateUserApiV1AdminUsersUserIdDeactivatePatchResponses[keyof DeactivateUserApiV1AdminUsersUserIdDeactivatePatchResponses];

export type GetOwnProfileApiV1UserProfileGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/profile';
};

export type GetOwnProfileApiV1UserProfileGetResponses = {
    /**
     * Successful Response
     */
    200: UserProfileResponse;
};

export type GetOwnProfileApiV1UserProfileGetResponse = GetOwnProfileApiV1UserProfileGetResponses[keyof GetOwnProfileApiV1UserProfileGetResponses];

export type ChatOwnApiV1SessionChatPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/session/chat';
};

export type ChatOwnApiV1SessionChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatOwnApiV1SessionChatPostError = ChatOwnApiV1SessionChatPostErrors[keyof ChatOwnApiV1SessionChatPostErrors];

export type ChatOwnApiV1SessionChatPostResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ChatOwnApiV1SessionChatPostResponse = ChatOwnApiV1SessionChatPostResponses[keyof ChatOwnApiV1SessionChatPostResponses];

export type NewChatApiV1SessionNewChatPostData = {
    body: NewChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/session/new-chat';
};

export type NewChatApiV1SessionNewChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewChatApiV1SessionNewChatPostError = NewChatApiV1SessionNewChatPostErrors[keyof NewChatApiV1SessionNewChatPostErrors];

export type NewChatApiV1SessionNewChatPostResponses = {
    /**
     * Successful Response
     */
    201: NewChatResponse;
};

export type NewChatApiV1SessionNewChatPostResponse = NewChatApiV1SessionNewChatPostResponses[keyof NewChatApiV1SessionNewChatPostResponses];

export type ContinueChatApiV1SessionContinueChatPostData = {
    body: ContinueChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/session/continue-chat';
};

export type ContinueChatApiV1SessionContinueChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ContinueChatApiV1SessionContinueChatPostError = ContinueChatApiV1SessionContinueChatPostErrors[keyof ContinueChatApiV1SessionContinueChatPostErrors];

export type ContinueChatApiV1SessionContinueChatPostResponses = {
    /**
     * Successful Response
     */
    200: ContinueChatResponse;
};

export type ContinueChatApiV1SessionContinueChatPostResponse = ContinueChatApiV1SessionContinueChatPostResponses[keyof ContinueChatApiV1SessionContinueChatPostResponses];

export type RenameOwnConversationApiV1SessionConversationsConvIdRenamePatchData = {
    body: RenameConversationRequest;
    path: {
        /**
         * Conv Id
         */
        conv_id: string;
    };
    query?: never;
    url: '/api/v1/session/conversations/{conv_id}/rename';
};

export type RenameOwnConversationApiV1SessionConversationsConvIdRenamePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenameOwnConversationApiV1SessionConversationsConvIdRenamePatchError = RenameOwnConversationApiV1SessionConversationsConvIdRenamePatchErrors[keyof RenameOwnConversationApiV1SessionConversationsConvIdRenamePatchErrors];

export type RenameOwnConversationApiV1SessionConversationsConvIdRenamePatchResponses = {
    /**
     * Successful Response
     */
    200: RenameConversationResponse;
};

export type RenameOwnConversationApiV1SessionConversationsConvIdRenamePatchResponse = RenameOwnConversationApiV1SessionConversationsConvIdRenamePatchResponses[keyof RenameOwnConversationApiV1SessionConversationsConvIdRenamePatchResponses];

export type ClearOwnSessionApiV1SessionConversationsConvIdDeleteData = {
    body?: never;
    path: {
        /**
         * Conv Id
         */
        conv_id: string;
    };
    query?: never;
    url: '/api/v1/session/conversations/{conv_id}';
};

export type ClearOwnSessionApiV1SessionConversationsConvIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ClearOwnSessionApiV1SessionConversationsConvIdDeleteError = ClearOwnSessionApiV1SessionConversationsConvIdDeleteErrors[keyof ClearOwnSessionApiV1SessionConversationsConvIdDeleteErrors];

export type ClearOwnSessionApiV1SessionConversationsConvIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type ClearOwnSessionApiV1SessionConversationsConvIdDeleteResponse = ClearOwnSessionApiV1SessionConversationsConvIdDeleteResponses[keyof ClearOwnSessionApiV1SessionConversationsConvIdDeleteResponses];

export type GetOwnConversationApiV1SessionConversationsConvIdGetData = {
    body?: never;
    path: {
        /**
         * Conv Id
         */
        conv_id: string;
    };
    query?: never;
    url: '/api/v1/session/conversations/{conv_id}';
};

export type GetOwnConversationApiV1SessionConversationsConvIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOwnConversationApiV1SessionConversationsConvIdGetError = GetOwnConversationApiV1SessionConversationsConvIdGetErrors[keyof GetOwnConversationApiV1SessionConversationsConvIdGetErrors];

export type GetOwnConversationApiV1SessionConversationsConvIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationHistoryResponse;
};

export type GetOwnConversationApiV1SessionConversationsConvIdGetResponse = GetOwnConversationApiV1SessionConversationsConvIdGetResponses[keyof GetOwnConversationApiV1SessionConversationsConvIdGetResponses];

export type ClearOwnSessionApiV1SessionDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/session';
};

export type ClearOwnSessionApiV1SessionDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type ClearOwnSessionApiV1SessionDeleteResponse = ClearOwnSessionApiV1SessionDeleteResponses[keyof ClearOwnSessionApiV1SessionDeleteResponses];

export type ListOwnConversationsApiV1SessionConversationsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/session/conversations';
};

export type ListOwnConversationsApiV1SessionConversationsGetResponses = {
    /**
     * Successful Response
     */
    200: UserConversationsResponse;
};

export type ListOwnConversationsApiV1SessionConversationsGetResponse = ListOwnConversationsApiV1SessionConversationsGetResponses[keyof ListOwnConversationsApiV1SessionConversationsGetResponses];

export type ChatAsTargetApiV1SessionChatTargetUserIdPostData = {
    body: ChatRequest;
    path: {
        /**
         * Target User Id
         */
        target_user_id: string;
    };
    query?: never;
    url: '/api/v1/session/chat/{target_user_id}';
};

export type ChatAsTargetApiV1SessionChatTargetUserIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatAsTargetApiV1SessionChatTargetUserIdPostError = ChatAsTargetApiV1SessionChatTargetUserIdPostErrors[keyof ChatAsTargetApiV1SessionChatTargetUserIdPostErrors];

export type ChatAsTargetApiV1SessionChatTargetUserIdPostResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ChatAsTargetApiV1SessionChatTargetUserIdPostResponse = ChatAsTargetApiV1SessionChatTargetUserIdPostResponses[keyof ChatAsTargetApiV1SessionChatTargetUserIdPostResponses];

export type ClearTargetSessionApiV1SessionTargetUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * Target User Id
         */
        target_user_id: string;
    };
    query?: never;
    url: '/api/v1/session/{target_user_id}';
};

export type ClearTargetSessionApiV1SessionTargetUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ClearTargetSessionApiV1SessionTargetUserIdDeleteError = ClearTargetSessionApiV1SessionTargetUserIdDeleteErrors[keyof ClearTargetSessionApiV1SessionTargetUserIdDeleteErrors];

export type ClearTargetSessionApiV1SessionTargetUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type ClearTargetSessionApiV1SessionTargetUserIdDeleteResponse = ClearTargetSessionApiV1SessionTargetUserIdDeleteResponses[keyof ClearTargetSessionApiV1SessionTargetUserIdDeleteResponses];

export type ListTargetConversationsApiV1SessionTargetUserIdConversationsGetData = {
    body?: never;
    path: {
        /**
         * Target User Id
         */
        target_user_id: string;
    };
    query?: never;
    url: '/api/v1/session/{target_user_id}/conversations';
};

export type ListTargetConversationsApiV1SessionTargetUserIdConversationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTargetConversationsApiV1SessionTargetUserIdConversationsGetError = ListTargetConversationsApiV1SessionTargetUserIdConversationsGetErrors[keyof ListTargetConversationsApiV1SessionTargetUserIdConversationsGetErrors];

export type ListTargetConversationsApiV1SessionTargetUserIdConversationsGetResponses = {
    /**
     * Successful Response
     */
    200: UserConversationsResponse;
};

export type ListTargetConversationsApiV1SessionTargetUserIdConversationsGetResponse = ListTargetConversationsApiV1SessionTargetUserIdConversationsGetResponses[keyof ListTargetConversationsApiV1SessionTargetUserIdConversationsGetResponses];

export type GetTargetConversationApiV1SessionTargetUserIdConversationsConvIdGetData = {
    body?: never;
    path: {
        /**
         * Target User Id
         */
        target_user_id: string;
        /**
         * Conv Id
         */
        conv_id: string;
    };
    query?: never;
    url: '/api/v1/session/{target_user_id}/conversations/{conv_id}';
};

export type GetTargetConversationApiV1SessionTargetUserIdConversationsConvIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTargetConversationApiV1SessionTargetUserIdConversationsConvIdGetError = GetTargetConversationApiV1SessionTargetUserIdConversationsConvIdGetErrors[keyof GetTargetConversationApiV1SessionTargetUserIdConversationsConvIdGetErrors];

export type GetTargetConversationApiV1SessionTargetUserIdConversationsConvIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationHistoryResponse;
};

export type GetTargetConversationApiV1SessionTargetUserIdConversationsConvIdGetResponse = GetTargetConversationApiV1SessionTargetUserIdConversationsConvIdGetResponses[keyof GetTargetConversationApiV1SessionTargetUserIdConversationsConvIdGetResponses];

export type RenameTargetConversationApiV1SessionTargetUserIdConversationsConvIdRenamePatchData = {
    body: RenameConversationRequest;
    path: {
        /**
         * Target User Id
         */
        target_user_id: string;
        /**
         * Conv Id
         */
        conv_id: string;
    };
    query?: never;
    url: '/api/v1/session/{target_user_id}/conversations/{conv_id}/rename';
};

export type RenameTargetConversationApiV1SessionTargetUserIdConversationsConvIdRenamePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenameTargetConversationApiV1SessionTargetUserIdConversationsConvIdRenamePatchError = RenameTargetConversationApiV1SessionTargetUserIdConversationsConvIdRenamePatchErrors[keyof RenameTargetConversationApiV1SessionTargetUserIdConversationsConvIdRenamePatchErrors];

export type RenameTargetConversationApiV1SessionTargetUserIdConversationsConvIdRenamePatchResponses = {
    /**
     * Successful Response
     */
    200: RenameConversationResponse;
};

export type RenameTargetConversationApiV1SessionTargetUserIdConversationsConvIdRenamePatchResponse = RenameTargetConversationApiV1SessionTargetUserIdConversationsConvIdRenamePatchResponses[keyof RenameTargetConversationApiV1SessionTargetUserIdConversationsConvIdRenamePatchResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type QueryDataApiV1QueryPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: string;
    };
    url: '/api/v1/query';
};

export type QueryDataApiV1QueryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QueryDataApiV1QueryPostError = QueryDataApiV1QueryPostErrors[keyof QueryDataApiV1QueryPostErrors];

export type QueryDataApiV1QueryPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
